### ISSUE TITLE
1.20.1 v1.1.6: Error upon joining

### ISSUE THREAD

**Issue by Skullians** [thecolonel63/server-side-replay-recorder#45] opened 2023-11-06 16:33 UTC
Upon joining, I get this error:

`[16:29:47] [Replay-Writer-2/ERROR]: Uncaught exception in thread "Replay-Writer-2"
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1934.method_8379()" because "this.comp_90" is null
        at net.minecraft.class_2678.method_11052(class_2678.java:74) ~[server-intermediary.jar:?]
        at com.thecolonel63.serversidereplayrecorder.recorder.ReplayRecorder._save(ReplayRecorder.java:370) ~[serversidereplayrecorder-1.1.6-mc1.20.jar:?]
        at com.thecolonel63.serversidereplayrecorder.recorder.ReplayRecorder.lambda$onServerTick$2(ReplayRecorder.java:322) ~[serversidereplayrecorder-1.1.6-mc1.20.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]`

**Comment by thecolonel63** [comment] 2023-11-06 16:59
Did you find out what was causing the error or did you close it accidentally?

**Comment by Skullians** [comment] 2023-11-06 19:37
I closed it as i fixed the issue, then it came back.

**Comment by thecolonel63** [comment] 2023-11-06 20:03
Looking more closely at this, it's probably happening because the GameJoinS2C packet is somehow returning null for the gamemode ID as it's saving the packet to the file - I'm not sure why this is happening as of now, but I'll come back and close this once I find out more info and fix it.

**Comment by thecolonel63** [comment] 2023-11-06 20:22
Okay so we've narrowed it down and the issue is likely caused by another mod modifying the packet before we can save it properly - Could you send the full list of all the mods you're using to cause the issue?

**Comment by Skullians** [comment] 2023-11-09 16:15
Sorry for the late reply!
It's probably one of my other mods.

- Carpet Extra
- Carpet Fixes
- Carpet TIS
- Cloth Config
- Clumps (XP Lag Reducer)
- Fabric API
- Carpet Mod
- Fabric Language Kotlin
- FerriteCore (Reduces RAM Usage)
- Lazy DFU (Improves server boot times)
- Lithium
- Memory Leak Fix
- **PCA Protocol** - most likely the problem, allows me to see inside inventories without me opening them.
- Starlight
- Syncmatica (Share litematics on the server)

**Comment by Skullians** [comment] 2023-11-09 16:30
I do get this:
`[16:29:52] [main/WARN]: @Mixin target carpet.patches.NetHandlerPlayServerFake was not found serversidereplayrecorder.mixins.json:player.NetHandlerPlayServerFakeMixin from mod serversidereplayrecorder`

**Comment by Skullians** [comment] 2023-11-09 16:31
@thecolonel63
Following that, I removed all mods apart from server-side-replay-recorder and I'm still getting the error.

**Comment by Skullians** [comment] 2023-11-09 16:31
the replay does appear in the folder, but it won't load on my client.

**Comment by thecolonel63** [comment] 2023-11-09 16:35
This is bizarre, because the issue should be impossible without something modifying the packet. As of right now I can't do anything to fix this, partially because I'm busy with something else, partially because I can't reproduce this issue on my end. I'll get back to you later.

**Comment by Skullians** [comment] 2023-11-09 18:46
No worries.
In case you need it, here is my server info:
- Server is ARM Based.
- 9216MB RAM Allocated
- Running in Pterodactyl (Docker)
- OpenJDK 17.0.9
- Minecraft Version 1.20.1
- Fabric Loader 0.14.24
- **Server Side Replay Recorder v1.1.6**

**Comment by thecolonel63** [comment] 2023-11-09 19:20
Update: We found the issue, the vanilla method switched the Gamemode and Previous Gamemode parameters, so the fix we have for render distance fog that rewrites the packet accidentally swapped them.

This should be fixed on the next release.

**Closed as completed by thecolonel63** 2023-11-09 19:20 UTC

**Comment by mattymatty97** [comment] 2023-11-09 19:26
while you wait for the next release you can disable `render_distance_fog_fix` in the config file.

we still suggest you to turn it back on once we upload the fixed mod

**Comment by Skullians** [comment] 2023-11-10 17:17
Alright, thankyou so much!
