### ISSUE TITLE
Player recording limit?/players not being recorded or saved correctly

### ISSUE THREAD

**Issue by DJMalachite** [thecolonel63/server-side-replay-recorder#34] opened 2023-07-04 00:26 UTC
Hey we added this mod to our server not too long ago but it looks as if some players are not being recorded on join or they are not having their replays saved correctly when we have "recording_enabled: true"

What we aim to have is automatic recording when a player joins and then have it saved once they leave
or have the entire server recorded into one file

At the moment we don't have clear documentation on how to do this or whether the mod is bugged and won't record more than 3 people at once

Please let me know how I can achieve this, thanks in advance.

here is our current config

```
#Config for Server Side Replay Recorder
##WARNING any comments in this file might get deleted

command_op_level: 4
replay_folder_name: "replay_recordings"
server_name: "My Server"
recordable_users: []
recording_enabled: true
assume_unloaded_chunks_dont_change: true
max_file_size: 10000000000
debug: false
use_username_for_recordings: true
invert_user_list: true
use_server_timestamps: true
render_distance_fog_fix: false
file_storage_url: "https://file.io/"
```

**Comment by DJMalachite** [comment] 2023-07-05 18:08
Should add that when a player joins it says recording started:"player" but when we check the status it is only 2 or three people being recorded

**Comment by mattymatty97** [comment] 2023-07-05 18:23
do you have the logfiles of the issue... we can't reproduce it as of now

**Comment by DJMalachite** [comment] 2023-07-05 18:43
Ahhh i can get them do you want them with the debug enabled or just logs?

> do you have the logfiles of the issue... we can't reproduce it as of now

**Comment by mattymatty97** [comment] 2023-07-05 18:53
no the debug option only adds stuff to the replayfile, i just need the normal logs to see if for some reason it is stopping the recorders early

also do the folders for the non recorded players generate too?

**Comment by DJMalachite** [comment] 2023-07-05 19:01
> no the debug option only adds stuff to the replayfile, i just need the normal logs to see if for some reason it is stopping the recorders early
> 
> also do the folders for the non recorded players generate too?

At a glance it looks like the folders are being created 

I will give you a log as soon as I am finished redacting ip's

**Comment by DJMalachite** [comment] 2023-07-05 19:09
[2023-07-05-1.log](https://github.com/thecolonel63/server-side-replay-recorder/files/11961102/2023-07-05-1.log)
Heres a log file

We host the server using shockbyte so that could be why the mod is throwing not enough space error however we should have unlimited space (128GB per server)


Currently we have this much for this instance 
![image](https://github.com/thecolonel63/server-side-replay-recorder/assets/69500602/15a3e198-a091-46a9-82b9-d633b452c677)

**Comment by mattymatty97** [comment] 2023-07-05 19:30
for what i can see the mod is working as intended except the occasionals `Not enough space left on device`
Which, if you left the default config, means that in the system there was less than `[Nplayers] * 10Gb`
that equals for 3 players to 30Gb so at that moment your disk was 430+ Gb full,
barely 10Gb more than the picture you send now.
I suggest to find a larger disk or to try and reduce the max_file_size parameter to some more reasonable value.

**Comment by thecolonel63** [comment] 2023-07-05 19:34
Since this is a spatial issue, I'm gonna go ahead and close this now.

Best of luck to you of finding a storage solution!

**Closed as completed by thecolonel63** 2023-07-05 19:34 UTC

**Comment by DJMalachite** [comment] 2023-07-05 19:40
Ahhh so its trying to allocate 10gb per player makes sense I didn't realise that's how it works 

We plan to only keep a few hours of recordings sooo ill try a smaller size 

Thank you :D
